"""create core course models

Revision ID: 1ce65bd53059
Revises: 4508fd1c189d
Create Date: 2026-09-25 11:50:45.493643

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ce65bd53059"
down_revision: str | Sequence[str] | None = "4508fd1c189d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("course_code", sa.String(length=20), nullable=False),
        sa.Column("course_name", sa.String(length=255), nullable=False),
        sa.Column(
            "collaboration_type",
            sa.Enum("individual", "team_based", name="collaboration_type"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("course_id"),
    )
    op.create_table(
        "course_offerings",
        sa.Column("offering_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column(
            "term",
            sa.Enum("fall", "winter", "summer", name="term_type"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.course_id"],
        ),
        sa.PrimaryKeyConstraint("offering_id"),
        sa.UniqueConstraint(
            "course_id", "term", "year", name="unique_course_offerings_course_term_year"
        ),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("student", "professor", name="profile_role"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "course_memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("offering_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "completed", "withdrawn", "removed", name="membership_status"
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.offering_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "offering_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_memberships")
    op.drop_table("profiles")
    op.drop_table("course_offerings")
    op.drop_table("courses")

    sa.Enum(name="membership_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="profile_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="term_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="collaboration_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
