"""add assessments

Revision ID: 26c94a6ec922
Revises: 1ce65bd53059
Create Date: 2026-10-04 11:28:17.704224

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26c94a6ec922"
down_revision: str | Sequence[str] | None = "1ce65bd53059"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    collaboration_type = postgresql.ENUM(
        "individual",
        "team_based",
        name="collaboration_type",
        create_type=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessments",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("offering_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "assessment_type",
            sa.Enum(
                "exam",
                "test",
                "quiz",
                "assignment",
                "programming_assignment",
                "lab",
                "report",
                "project",
                "project_checkpoint",
                "presentation",
                "discussion",
                "other",
                name="assessment_type",
            ),
            nullable=False,
        ),
        sa.Column("assessment_type_label", sa.String(length=255), nullable=True),
        sa.Column(
            "collaboration_type",
            collaboration_type,
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at > starts_at",
            name="ck_assessments_end_after_start",
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NOT NULL",
            name="ck_assessments_end_requires_start",
        ),
        sa.CheckConstraint(
            "weight IS NULL OR (weight >= 0 AND weight <= 100)",
            name="ck_assessments_weight_range",
        ),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.offering_id"],
        ),
        sa.PrimaryKeyConstraint("assessment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assessments")
    sa.Enum(name="assessment_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
